spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/treat?characterEncoding=UTF-8&serverTimezone=UTC
    username: yujin
    password: 1q2w3e4r

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  jwt:
    header: Authorization
    secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM
    accessTokenValidityInSeconds: 3600