spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apiserver?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create # (1) 스키마 자동 생성
    show-sql: true # (2) SQL 쿼리 출력
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print

    defer-datasource-initialization: true

jwt:
  header: Authorization
  secret: RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!